#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config border_width 0
bspc config window_gap 0

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# Regla para la ventana Quake (oculta al inicio)
bspc rule -a "kitty:quake_kitty" state=floating sticky=on border=off hidden=on

# Iniciar kitty en segundo plano al arrancar
kitty -1 --class "quake_kitty" zsh &

# Fondo de pantalla
feh --no-fehbg --bg-scale '/usr/share/backgrounds/macos-catalina-mountains-island-morning-stock-5k-1920x1080-4015.jpg' &

# Iniciar script OSD
~/.config/bspwm/scripts/bspwm_osd.sh &

# Iniciar compositor de ventanas
picom --config ~/.config/picom/picom.conf &
