# --- Configuración OSD ---
BATTERY_PATH="/sys/class/power_supply/axp288_fuel_gauge"
MAX_BRIGHTNESS=1200
BRIGHTNESS_STEP=50
MAX_VOLUME=150
DURATION_MS=2000
BAR_LENGTH=8

# IDs para dunstify (evitar colisiones)
ID_VOLUME=3
ID_BRIGHTNESS=4
ID_BATTERY=4
ID_DESKTOP=1
ID_NETWORK=5
